language: c

script:
 - sudo pip install cpp-coveralls
 - autoreconf && ( if [ "$CC" = gcc ]; then ./configure --enable-coverage; else ./configure; fi ) && make -j4 && make check

compiler:
 - gcc
 - clang

after_success:
 - if [ "$CC" = gcc ]; then coveralls --encoding iso-8859-1 --build-root src/ --gcov-options '\-p'; fi

notifications:
  email:
    recipients:
      - xaizek@openmailbox.org
